#! /bin/sh

## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+
##         _    _                            _                        |
##        / \  | |__  _   _ _ __   __ _  ___| |__   __ _ _ __         |
##       / _ \ | '_ \| | | | '_ \ / _` |/ __| '_ \ / _` | '__|        |
##      / ___ \| |_) | |_| | | | | (_| | (__| | | | (_| | |           |
##     /_/   \_\_.__/ \__,_|_| |_|\__,_|\___|_| |_|\__,_|_|           |
##                                                                    |
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+~~~~~~~~~~~~~~~~~+
##                                                  |
##  FILENAME : bspwmrc                              |
##  AUTHOR   : Abunachar ( Knight-Byte )            |
##  GITHUB   : https://www.github.com/knight-byte   |
##                                                  |
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+

# Startup Hook {{{

pgrep -x sxhkd > /dev/null || sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh &
picom &
xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/forest/launch.sh
copyq &
xmodmap .Xmodmap &
dunst &
greenclip daemon &
# }}}

# Wallpaper {{{

# feh --bg-scale $HOME/wallpapers/archlogo.png & # -- arch logo
# feh --bg-scale $HOME/wallpapers/cybrorg.png #-- cybrorg
# feh --bg-scale $HOME/wallpapers/samurai.jpg & # -- samurai
# feh --bg-scale $HOME/wallpapers/Kimiko.jpg & # -- kylo
# feh --bg-scale $HOME/wallpapers/feather.jpg & # -- feather
# feh --bg-scale $HOME/wallpapers/catgirl.png & # -- cat-girl
# feh --bg-scale $HOME/wallpapers/rooflinesgirl.jpg & # -- rooflinesgirl
# feh --bg-scale $HOME/wallpapers/linuxlogo.png & # --linux logo
# feh --bg-scale $HOME/wallpapers/space.jpg & # -- space guy
# feh --bg-scale $HOME/wallpapers/whitecurtain.jpg & # -- whitecurtain
# feh --bg-scale $HOME/wallpapers/the-neon-shallows-redish.png & # -- tokyoNight city
feh --bg-scale $HOME/wallpapers/gruv_waifu.jpg & # -- gruv waifu
# feh --bg-scale $HOME/wallpapers/blueGirl.jpg & # -- Blue girl
# feh --bg-scale $HOME/wallpapers/tokyoNight.jpg & # -- tokyoNight

# }}}

# Workspaces {{{

bspc monitor -d Fire Water Wind Earth Space

# }}}

# Window Config {{{

bspc config border_width         3
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bsp-layout set monocle
# }}}

# Window Rules {{{

bspc rule -a Gimp desktop='^3' state=floating follow=on
# bspc rule -a firefox desktop='^5'
# bspc rule -a TelegramDesktop state=floating
bspc rule -a "VirtualBox Machine" state=floating
bspc config external_rules_command $HOME/.config/bspwm/emulator_rule

# }}}
